name: Security Image Scan

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t local/securitytest:latest .

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: local/securitytest:latest
          scanners: vuln
          vuln-type: os,library
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table
          output: trivy-results.txt
          exit-code: 1

      - name: Create PR Summary
        if: github.event_name == 'pull_request'
        run: |
          {
            echo "## Trivy Image Vulnerability Scan"
            echo
            echo '```text'
            cat trivy-results.txt
            echo '```'
          } > comment.md

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: trivy-image-scan
          recreate: true
          path: comment.md
